### ISSUE TITLE
Syntax error running PRET from Termux on Android

### ISSUE THREAD

**Issue by RadArcTan** [RUB-NDS/PRET#11]
I am trying to run PRET in Termux(busy box) on Android, all newest versions installed today.

I get the following:
$ python pret.py
Traceback (most recent call last):
  File "pret.py", line 8, in <module>
    from discovery import discovery
  File "/data/data/com.termux/files/home/PRET/discovery.py", line 7, in <module>
    from helper import output, conv
  File "/data/data/com.termux/files/home/PRET/helper.py", line 130
    def discover(self, (ipaddr, (device, uptime, status, prstat))):
                       ^
SyntaxError: invalid syntax

I am a beginner at programming... Any help here would be much appreciated.

**Comment by ingamx** [comment]
Kk

**Comment by Hugo22O** [comment]
You need to install colorama and pysnm by using the command `pip`2 install colorama pysnmp` instead of `pip install [dependencies]` then run pret.py with: `python2 pret.py` instead of using `python pret.py` 

Pret only works with Python2 if you type `python` it won't work. 


To spare others time installing PRET on Termux I wrote a guide: https://github.com/Hugo22O/A-Guide-To-Install-PRET-on-Termux

Check out the guide as well if you're still getting errors.
