### ISSUE TITLE
Can't specify port with lpdtest.py

### ISSUE THREAD

**Issue by skilfoy** [RUB-NDS/PRET#59]
Whether I change the default port in the script from 515 to (for example) 30886 or if I specify the port in the bash command with the option --port 30886, I get the same error:

> Traceback (most recent call last):
>   File "lpdtest.py", line 185, in <module>
>     s.send(bytes("\002"+queue+"\n",'utf-8'))
> TypeError: str() takes at most 1 argument (2 given)

If I don't specify the port, the script seems to fire off, although the print server is not on port 515, so nothing happens, but I don't get an error. The error only occurs when I specify the port. 

Why does changing the port number make the script think that there's an additional argument? And how can this be fixed?

**Comment by 0xWerz** [comment]
you may just need to edit the script :D, specifically change the `default` variable the line 48.
` parser.add_argument("--port", type=int,    help="printer port",default=30886 )`

**Comment by e1e0** [comment]
Reserved shell word "in" ? File "./lpd/lpdtest.py", line 185 - `TypeError`.
